Add deploySC from bearby account
massalabs/wallet-provider pull request #261
Opened 2024-11-20 18:21 UTC by pivilartisant

2024-11-20 20:28 UTC, pivilartisant commented
the tests don't seem to like these imports: 
// import { DEPLOYER_BYTECODE } from '@massalabs/massa-web3/dist/esm/generated/deployer-bytecode';
// import * as StorageCost from '@massalabs/massa-web3/dist/esm/basicElements/storage';

With error
```Jest encountered an unexpected token```

2024-11-20 23:56 UTC, peterjah requested changes

2024-11-20 23:56 UTC, peterjah commented on jest.e2e.config.esm.js
> -    'node_modules/(?!(@massalabs/wallet-provider|@hicaru/bearby.js|big-varint)/)',
why ?

2024-11-20 23:56 UTC, peterjah commented on src/bearbyWallet/BearbyAccount.ts
> +import * as StorageCost from '@massalabs/massa-web3/dist/esm/basicElements/storage';
do not import things from dist

2024-11-21 16:26 UTC, pivilartisant commented
blocked by: https://github.com/massalabs/massa-web3/pull/703

2024-11-21 20:49 UTC, peterjah requested changes

2024-12-03 14:14 UTC, closed without merging