38 add 'verifysignature' to the account class
massalabs/wallet-provider pull request #39
Opened 2023-05-10 08:22 UTC by Elli610

2023-05-19 08:18 UTC, Ben-Rey requested changes

2023-05-19 08:18 UTC, Ben-Rey commented on src/account/Account.ts
> +   * @returns true if the signature is valid, false otherwise
```suggestion
   * @returns A Promise that resolves to true if the signature is valid, and false otherwise.
```

2023-05-19 08:26 UTC, Ben-Rey approved these changes

2023-06-08 13:25 UTC, Elli610 commented
> @Elli610 @Ben-Rey Why do we need a verify signature ?

This is a features I worked on several weeks ago. Maybe it was complementary to the signing function ¯⁠\⁠_⁠ʘ⁠‿⁠ʘ⁠_⁠/⁠¯

2023-07-26 20:40 UTC, closed without merging