Interact with smart contract
massalabs/wallet-provider pull request #41
Opened 2023-05-12 13:02 UTC by Elli610

closes #35

2023-05-19 07:39 UTC, Ben-Rey approved these changes

2023-05-19 12:40 UTC, gregLibert requested changes

2023-05-19 12:40 UTC, gregLibert commented on src/account/Account.ts
> +          fee,
I don't think you can pass a bigInt to the extension: this object is not JSON serailizable. You should chnage its type here to a string

2023-05-19 12:40 UTC, gregLibert commented on src/account/Account.ts
> +          parameter,
Same as below, if the type is a BigInt you should consert it to a string instead. This is the bug we encountered testing the wallet provider with chromium in the CI last time!

2023-05-22 09:05 UTC, gregLibert approved these changes

2023-05-22 09:05 UTC, merged