display the entire error message when post request fail
massalabs/wallet-provider pull request #51
Opened 2023-06-05 14:54 UTC by Elli610

2023-06-05 18:03 UTC, Ben-Rey requested changes

2023-06-05 18:03 UTC, Ben-Rey commented on src/thyra/RequestHandler.ts
> +    try {
maybe this but it remove a console.log

```typescript
export async function postRequest<T>(
  url: string,
  body: object,
): Promise<JsonRpcResponseData<T>> {
  try {
    const resp = await axios.post<unknown, AxiosResponse, object>(
      url,
      body,
      requestHeaders,
    );

    return {
      isError: false,
      result: resp.data as T,
      error: null,
    } as JsonRpcResponseData<T>;
  } catch (ex) {
    console.error('Error parsing response data or network error');
    
    return {
      isError: true,
      result: null,
      error: ex.response?.data?.message
        ? new Error(String(ex.response.data.message))
        : new Error('Axios error: ' + String(ex)),
    } as JsonRpcResponseData<T>;
  }
  ```

2023-06-05 18:03 UTC, Ben-Rey commented on src/thyra/RequestHandler.ts
> +    try {
These are just ideas, but I think this code could be lighter.

2023-06-06 08:12 UTC, Ben-Rey approved these changes

2023-06-06 09:35 UTC, julienbrs approved these changes

2023-06-07 16:16 UTC, gregLibert approved these changes

2023-06-07 16:16 UTC, merged